services:
  velocity:
    image: ghcr.io/florke-smp/velocity:latest
    container_name: velocity
    restart: unless-stopped
    network_mode: bridge
    
    ports:
      - "25565:25565"
    volumes:
      - velocity:/velocity

volumes:
  velocity:

