name: Build Latest Velocity Build

on:
  # Trigger every day at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
  
  # Also trigger on pushes to main branch
  push:
    branches: [ main ]

jobs:
  build:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Build the Docker image
      run: |
        ./update-velocity.sh

        source .buildargs
        
        echo "Building with:"
        echo "VELOCITY_URL: $VELOCITY_URL"
        echo "SHA256: $SHA256"
        
        # Build the Docker image
        docker build \
          --build-arg VELOCITY_URL="$VELOCITY_URL" \
          --build-arg SHA256="$SHA256" \
          -t velocity:latest \
          -t velocity:$(date +%Y%m%d-%H%M%S) \
          .
    
    - name: Push to GitHub Container Registry
      run: |
        REPO_ID=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')

        source .buildargs

        docker tag velocity:latest ghcr.io/$REPO_ID:latest
        docker tag ghcr.io/$REPO_ID:latest ghcr.io/$REPO_ID:$LATEST_VERSION
        docker push ghcr.io/$REPO_ID:latest
        docker push ghcr.io/$REPO_ID:$LATEST_VERSION
    
    - name: Docker system prune
      run: docker system prune -f