name: Latest Velocity

on:
  # Trigger every day at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Build and push the Docker image
      run: |
        ./update-velocity.sh

        source .buildargs
        
        echo "Building with:"
        echo "VELOCITY_URL: $VELOCITY_URL"
        echo "SHA256: $SHA256"
        
        # Build the Docker image
        docker build \
          --build-arg VELOCITY_URL="$VELOCITY_URL" \
          --build-arg SHA256="$SHA256" \
          -t ghcr.io/florke-smp/velocity:latest \
          -t ghcr.io/florke-smp/velocity:latest:$LATEST_VERSION \
          .

        docker push ghcr.io/florke-smp/velocity:latest
        docker push ghcr.io/florke-smp/velocity:$LATEST_VERSION
    
    - name: Docker system prune
      run: docker system prune -f